version: "3.0"

services:
  influx-db:
    image: influxdb
    environment:
      - INFLUXDB_DB=home
      - INFLUXDB_USER=spring
      - INFLUXDB_USER_PASSWORD=srping
    ports:
      - "8086:8086"
    volumes:
      - /home/pi/volumes/influxdb:/var/lib/influxdb
    networks:
      - network_home
  mysql-db:
    image: hypriot/rpi-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=spring
      - MYSQL_DATABASE=home
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=spring
    ports:
      - "3306:3306"
    networks:
      - network_home
    volumes:
      - /home/pi/volumes/mysql:/var/lib/mysql
  home-backend:
    image: localhost:5000/home-application:latest
    depends_on:
      - influx-db
      - mysql-db
    ports :
      - "8080:8080"
    networks:
      - network_home

volumes:
  volume_home:

networks:
  network_home:
